# Generated by Django 5.1.2 on 2024-11-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('operator', 'Оператор'), ('instructor', 'Инструктор'), ('admin', 'Администратор')], default='operator', max_length=20),
        ),
    ]
