# Generated by Django 5.1.2 on 2024-11-14 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_alter_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='lecture_files/')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='training.lecture')),
            ],
        ),
    ]
