# Generated by Django 5.1.2 on 2024-11-18 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0014_lecturefile_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturefile',
            name='uploaded_at',
        ),
    ]
